*KEYWORD
*PART
$#                                                             heading
Left ventricle                                                        
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         1         1         0                                                 1
*MAT_THERMAL_ISOTROPIC
$#    tmid        ro     tgrlc    tgmult      tlat      hlat
         1                                                  
$#      hc        tc
       1.0       1.0
*PART
$#                                                             heading
Right ventricle                                                       
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         2         1         0                                                 2
*MAT_THERMAL_ISOTROPIC
$#    tmid        ro     tgrlc    tgmult      tlat      hlat
         2                                                  
$#      hc        tc
       1.0       1.0
*PART
$#                                                             heading
Septum                                                                
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         5         1         0                                                 5
*MAT_THERMAL_ISOTROPIC
$#    tmid        ro     tgrlc    tgmult      tlat      hlat
         5                                                  
$#      hc        tc
       1.0       1.0
*SECTION_SOLID
$#   secid    elform       aet    unused    unused    unused    cohoff   gaskeit
         1        10         0                                                  
*END