*KEYWORD
*MAT_295
$nu deduced from kappa=1.0
$#     mid       rho      aopt
         1     0.001       2.0
$#   title     itype      beta        nu
ISO               -3       2.00.49882093
$#      k1        k2
   0.00236      1.75
$#   title     atype    intype        nf
ANISO             -1         0         1
$#   theta         a         b
       0.0       0.0       1.0
$#   ftype      fcid        k1        k2
         1         0   0.00049      9.01
$#      xp        yp        zp        a1        a2        a3      macf    unused
                                     1.0       0.0       0.0         1          
$#      v1        v2        v3        d1        d2        d3      beta       ref
                                     0.0       1.0       0.0                    
*MAT_295
$nu deduced from kappa=1.0
$#     mid       rho      aopt
         2     0.001       2.0
$#   title     itype      beta        nu
ISO               -3       2.00.49882093
$#      k1        k2
   0.00236      1.75
$#   title     atype    intype        nf
ANISO             -1         0         1
$#   theta         a         b
       0.0       0.0       1.0
$#   ftype      fcid        k1        k2
         1         0   0.00049      9.01
$#      xp        yp        zp        a1        a2        a3      macf    unused
                                     1.0       0.0       0.0         1          
$#      v1        v2        v3        d1        d2        d3      beta       ref
                                     0.0       1.0       0.0                    
*MAT_295
$nu deduced from kappa=1.0
$#     mid       rho      aopt
         7     0.001       2.0
$#   title     itype      beta        nu
ISO               -3       2.00.49882093
$#      k1        k2
   0.00236      1.75
$#   title     atype    intype        nf
ANISO             -1         0         1
$#   theta         a         b
       0.0       0.0       1.0
$#   ftype      fcid        k1        k2
         1         0   0.00049      9.01
$#      xp        yp        zp        a1        a2        a3      macf    unused
                                     1.0       0.0       0.0         1          
$#      v1        v2        v3        d1        d2        d3      beta       ref
                                     0.0       1.0       0.0                    
*MAT_295
$nu deduced from kappa=10.0
$#     mid       rho      aopt
         3     0.001       2.0
$#   title     itype      beta        nu
ISO               -1       2.00.49501661
$#     mu1       mu2       mu3       mu4       mu5       mu6       mu7       mu8
       0.1                                                                      
$#  alpha1    alpha2    alpha3    alpha4    alpha5    alpha6    alpha7    alpha8
       2.0                                                                      
*MAT_295
$nu deduced from kappa=10.0
$#     mid       rho      aopt
         4     0.001       2.0
$#   title     itype      beta        nu
ISO               -1       2.00.49501661
$#     mu1       mu2       mu3       mu4       mu5       mu6       mu7       mu8
       0.1                                                                      
$#  alpha1    alpha2    alpha3    alpha4    alpha5    alpha6    alpha7    alpha8
       2.0                                                                      
*MAT_295
$nu deduced from kappa=10.0
$#     mid       rho      aopt
         5     0.001       2.0
$#   title     itype      beta        nu
ISO               -1       2.00.49501661
$#     mu1       mu2       mu3       mu4       mu5       mu6       mu7       mu8
       0.1                                                                      
$#  alpha1    alpha2    alpha3    alpha4    alpha5    alpha6    alpha7    alpha8
       2.0                                                                      
*MAT_295
$nu deduced from kappa=10.0
$#     mid       rho      aopt
         6     0.001       2.0
$#   title     itype      beta        nu
ISO               -1       2.00.49501661
$#     mu1       mu2       mu3       mu4       mu5       mu6       mu7       mu8
       0.1                                                                      
$#  alpha1    alpha2    alpha3    alpha4    alpha5    alpha6    alpha7    alpha8
       2.0                                                                      
*END