*KEYWORD
*EM_EP_PURKINJE_NETWORK2
$#  purkid  buildnet      ssid       mid nodestart  pointstx  pointsty  pointstz
         1         1         3         4           66.301918 75.908388 352.83355
$# edgelen      ngen   nbrinit    nsplit   inodeid   iedgeid
         2        50         8         2     49830    233154
$# pmjtype pmjradiuspmjrestype    pmjres
         1       0.7         1     0.001
*EM_EP_PURKINJE_NETWORK2
$#  purkid  buildnet      ssid       mid nodestart  pointstx  pointsty  pointstz
         2         1         5         5           46.085562 77.419772 334.10097
$# edgelen      ngen   nbrinit    nsplit   inodeid   iedgeid
         2        50         8         2     99658    466306
$# pmjtype pmjradiuspmjrestype    pmjres
         1       0.7         1     0.001
*INCLUDE
$#                                                                      filename
parts.k                                                                         
*INCLUDE
$#                                                                      filename
nodes.k                                                                         
*INCLUDE
$#                                                                      filename
solid_elements.k                                                                
*INCLUDE
$#                                                                      filename
material.k                                                                      
*INCLUDE
$#                                                                      filename
segment_sets.k                                                                  
*INCLUDE
$#                                                                      filename
node_sets.k                                                                     
*INCLUDE
$#                                                                      filename
ep_settings.k                                                                   
*END