version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
#    insecure-external-code-execution: allow
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
      - "dependencies"
    ignore:
      - dependency-name: "vtk"
      - dependency-name: "grpcio"

    assignees:
      - "pyansys-ci-bot"
    commit-message:
      prefix: "MAINT"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "pyansys-ci-bot"
    commit-message:
      prefix: "MAINT"
