version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "maintenance"
      - "dependencies"
    ignore:
      - dependency-name: "vtk"
      - dependency-name: "grpcio"
    assignees:
      - "pyansys-ci-bot"
    commit-message:
      prefix: "build(deps):"
    groups:
      docs-deps:
          patterns:
            - "ansys-sphinx-theme*"
            - "ipyvtklink"
            - "jupyter_sphinx"
            - "jupytext"
            - "myst-parser"
            - "nbconvert"
            - "nbsphinx"
            - "notebook"
            - "numpydoc"
            - "sphinx"
            - "sphinx*"


  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
    assignees:
      - "pyansys-ci-bot"
    commit-message:
      prefix: "ci"
    groups:
       actions:
          patterns:
            - "*"
