*KEYWORD
*MAT_295
$#     mid       rho      aopt
         1     0.001       2.0
$#   title     itype      beta        nu
ISO               -3       0.0     0.499
$#      k1        k2
   0.00236      1.75
$#   title     atype    intype        nf
ANISO             -1         0         1
$#   theta         a         b
       0.0       0.0       1.0
$#   ftype      fcid        k1        k2
         1         0   0.00049      9.01
$#   title    actype     acdir      acid     acthr        sf        ss        sn
ACTIVE             3         1              0.0002       1.0       0.0       0.0
$#      t0    ca2ion  ca2ion50         n    sigmax         f         l       eta
                         0.001       2.0     0.125       0.0       1.9      1.45
$#      xp        yp        zp        a1        a2        a3      macf    unused
                                     1.0       0.0       0.0         1          
$#      v1        v2        v3        d1        d2        d3      beta       ref
                                     0.0       1.0       0.0                    
*MAT_295
$#     mid       rho      aopt
         2     0.001       2.0
$#   title     itype      beta        nu
ISO               -3       0.0     0.499
$#      k1        k2
   0.00236      1.75
$#   title     atype    intype        nf
ANISO             -1         0         1
$#   theta         a         b
       0.0       0.0       1.0
$#   ftype      fcid        k1        k2
         1         0   0.00049      9.01
$#   title    actype     acdir      acid     acthr        sf        ss        sn
ACTIVE             3         1              0.0002       1.0       0.0       0.0
$#      t0    ca2ion  ca2ion50         n    sigmax         f         l       eta
                         0.001       2.0     0.125       0.0       1.9      1.45
$#      xp        yp        zp        a1        a2        a3      macf    unused
                                     1.0       0.0       0.0         1          
$#      v1        v2        v3        d1        d2        d3      beta       ref
                                     0.0       1.0       0.0                    
*MAT_295
$#     mid       rho      aopt
         7     0.001       2.0
$#   title     itype      beta        nu
ISO               -3       0.0     0.499
$#      k1        k2
   0.00236      1.75
$#   title     atype    intype        nf
ANISO             -1         0         1
$#   theta         a         b
       0.0       0.0       1.0
$#   ftype      fcid        k1        k2
         1         0   0.00049      9.01
$#   title    actype     acdir      acid     acthr        sf        ss        sn
ACTIVE             3         1              0.0002       1.0       0.0       0.0
$#      t0    ca2ion  ca2ion50         n    sigmax         f         l       eta
                         0.001       2.0     0.125       0.0       1.9      1.45
$#      xp        yp        zp        a1        a2        a3      macf    unused
                                     1.0       0.0       0.0         1          
$#      v1        v2        v3        d1        d2        d3      beta       ref
                                     0.0       1.0       0.0                    
*MAT_295
$#     mid       rho      aopt
         3     0.001       2.0
$#   title     itype      beta        nu
ISO               -3       0.0     0.499
$#      k1        k2
   0.00236      1.75
$#   title     atype    intype        nf
ANISO             -1         0         1
$#   theta         a         b
       0.0       0.0       1.0
$#   ftype      fcid        k1        k2
         1         0   0.00049      9.01
$#   title    actype     acdir      acid     acthr        sf        ss        sn
ACTIVE             3         1              0.0002       1.0       0.0       0.0
$#      t0    ca2ion  ca2ion50         n    sigmax         f         l       eta
                         0.001       2.0     0.125       0.0       1.9      1.45
$#      xp        yp        zp        a1        a2        a3      macf    unused
                                     1.0       0.0       0.0         1          
$#      v1        v2        v3        d1        d2        d3      beta       ref
                                     0.0       1.0       0.0                    
*MAT_295
$#     mid       rho      aopt
         4     0.001       2.0
$#   title     itype      beta        nu
ISO               -3       0.0     0.499
$#      k1        k2
   0.00236      1.75
$#   title     atype    intype        nf
ANISO             -1         0         1
$#   theta         a         b
       0.0       0.0       1.0
$#   ftype      fcid        k1        k2
         1         0   0.00049      9.01
$#   title    actype     acdir      acid     acthr        sf        ss        sn
ACTIVE             3         1              0.0002       1.0       0.0       0.0
$#      t0    ca2ion  ca2ion50         n    sigmax         f         l       eta
                         0.001       2.0     0.125       0.0       1.9      1.45
$#      xp        yp        zp        a1        a2        a3      macf    unused
                                     1.0       0.0       0.0         1          
$#      v1        v2        v3        d1        d2        d3      beta       ref
                                     0.0       1.0       0.0                    
*MAT_077_H
$#     mid        ro        pr         n        nv         g      sigf       ref
         5     0.001     0.499         0                                     0.0
$#     c10       c01       c11       c20       c02       c30    therml
      0.05                                                            
*MAT_077_H
$#     mid        ro        pr         n        nv         g      sigf       ref
         6     0.001     0.499         0                                     0.0
$#     c10       c01       c11       c20       c02       c30    therml
      0.05                                                            
*MAT_295
$#     mid       rho      aopt
         8     0.001       2.0
$#   title     itype      beta        nu
ISO               -3       0.0     0.499
$#      k1        k2
   0.00236      1.75
$#   title     atype    intype        nf
ANISO             -1         0         1
$#   theta         a         b
       0.0       0.0       1.0
$#   ftype      fcid        k1        k2
         1         0   0.00049      9.01
$#      xp        yp        zp        a1        a2        a3      macf    unused
                                     1.0       0.0       0.0         1          
$#      v1        v2        v3        d1        d2        d3      beta       ref
                                     0.0       1.0       0.0                    
$$ Left ventricle $$
*EM_MAT_003
$#     mid     mtype   sigma11   sigma22   sigma33      beta        cm
         1         2       0.5       0.1       0.1     140.0      0.01
$# sigma12   sigma13   sigma21   sigma23   sigma31   sigma32      aopt   lambda_
                                                                     2          
$#      xp        yp        zp        a1        a2        a3      macf
                                     0.0       0.0       1.0         1
$#      v1        v2        v3        d1        d2        d3
                                     0.0      -1.0       0.0
$$ Right ventricle $$
*EM_MAT_003
$#     mid     mtype   sigma11   sigma22   sigma33      beta        cm
         2         2       0.5       0.1       0.1     140.0      0.01
$# sigma12   sigma13   sigma21   sigma23   sigma31   sigma32      aopt   lambda_
                                                                     2          
$#      xp        yp        zp        a1        a2        a3      macf
                                     0.0       0.0       1.0         1
$#      v1        v2        v3        d1        d2        d3
                                     0.0      -1.0       0.0
$$ Septum $$
*EM_MAT_003
$#     mid     mtype   sigma11   sigma22   sigma33      beta        cm
         7         2       0.5       0.1       0.1     140.0      0.01
$# sigma12   sigma13   sigma21   sigma23   sigma31   sigma32      aopt   lambda_
                                                                     2          
$#      xp        yp        zp        a1        a2        a3      macf
                                     0.0       0.0       1.0         1
$#      v1        v2        v3        d1        d2        d3
                                     0.0      -1.0       0.0
$$ Left atrium $$
*EM_MAT_003
$#     mid     mtype   sigma11   sigma22   sigma33      beta        cm
         3         2       0.5       0.1       0.1     140.0      0.01
$# sigma12   sigma13   sigma21   sigma23   sigma31   sigma32      aopt   lambda_
                                                                     2          
$#      xp        yp        zp        a1        a2        a3      macf
                                     0.0       0.0       1.0         1
$#      v1        v2        v3        d1        d2        d3
                                     0.0      -1.0       0.0
$$ Right atrium $$
*EM_MAT_003
$#     mid     mtype   sigma11   sigma22   sigma33      beta        cm
         4         2       0.5       0.1       0.1     140.0      0.01
$# sigma12   sigma13   sigma21   sigma23   sigma31   sigma32      aopt   lambda_
                                                                     2          
$#      xp        yp        zp        a1        a2        a3      macf
                                     0.0       0.0       1.0         1
$#      v1        v2        v3        d1        d2        d3
                                     0.0      -1.0       0.0
$$ Aorta $$
*EM_MAT_001
$#     mid     mtype     sigma     eosid    unused   lambda_    deatht   rdltype
         5         4       0.5                                   1e+28         0
$#   empty      freq     epsrr    eosid2     epsri    eosid3      eps0
                                                                      
$#    beta        cm
     140.0      0.01
$$ Pulmonary artery $$
*EM_MAT_001
$#     mid     mtype     sigma     eosid    unused   lambda_    deatht   rdltype
         6         4       0.5                                   1e+28         0
$#   empty      freq     epsrr    eosid2     epsri    eosid3      eps0
                                                                      
$#    beta        cm
     140.0      0.01
$$ Atrioventricular isolation $$
*EM_MAT_001
$#     mid     mtype     sigma     eosid    unused   lambda_    deatht   rdltype
         8         1       0.0                                   1e+28         0
$#   empty      freq     epsrr    eosid2     epsri    eosid3      eps0
                                                                      
$#    beta        cm
       0.0       0.0
*END