*KEYWORD
*PART
$#                                                             heading
Left ventricle
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         1         1         1
*PART
$#                                                             heading
Right ventricle
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         2         1         1
*PART
$#                                                             heading
Septum
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         3         1         1
*SECTION_SOLID
$#   secid    elform       aet                                  cohoff   gaskeit
         1        13         0
*END