*KEYWORD
*MAT_295
$#     mid       rho      aopt
         1     1e-06       2.0
$#   title     itype      beta        nu
ISO               -3       0.0     0.499
$#      k1        k2
      2.36      1.75
$#   title     atype    intype        nf
ANISO             -1         0         1
$#   theta         a         b
       0.0      0.08      0.76
$#   ftype      fcid        k1        k2
         1         0      0.49      9.01
$#      xp        yp        zp        a1        a2        a3      macf
                                                                     1
$#      v1        v2        v3        d1        d2        d3      beta       ref
                                                                                
*MAT_295
$#     mid       rho      aopt
         2     1e-06       2.0
$#   title     itype      beta        nu
ISO               -3       0.0     0.499
$#      k1        k2
      2.36      1.75
$#   title     atype    intype        nf
ANISO             -1         0         1
$#   theta         a         b
       0.0      0.08      0.76
$#   ftype      fcid        k1        k2
         1         0      0.49      9.01
$#      xp        yp        zp        a1        a2        a3      macf
                                                                     1
$#      v1        v2        v3        d1        d2        d3      beta       ref
                                                                                
*MAT_295
$#     mid       rho      aopt
         3     1e-06       2.0
$#   title     itype      beta        nu
ISO               -3       0.0     0.499
$#      k1        k2
      2.36      1.75
$#   title     atype    intype        nf
ANISO             -1         0         1
$#   theta         a         b
       0.0      0.08      0.76
$#   ftype      fcid        k1        k2
         1         0      0.49      9.01
$#      xp        yp        zp        a1        a2        a3      macf
                                                                     1
$#      v1        v2        v3        d1        d2        d3      beta       ref
                                                                                
*END