*KEYWORD
*PART
$#                                                             heading
Left atrium                                                           
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         3         1         0                                                 3
*MAT_THERMAL_ISOTROPIC
$#    tmid        ro     tgrlc    tgmult      tlat      hlat
         3                                                  
$#      hc        tc
       1.0       1.0
*SECTION_SOLID
$#   secid    elform       aet    unused    unused    unused    cohoff   gaskeit
         1        10         0                                                  
*END