*KEYWORD
*MAT_ELASTIC
$#     mid        ro         e        pr        da        db    unused
         1     1e-06       1.0                                        
*EM_MAT_003
$#     mid     mtype   sigma11   sigma22   sigma33      beta        cm
         1         2       0.5       0.1       0.1     140.0      0.01
$# sigma12   sigma13   sigma21   sigma23   sigma31   sigma32      aopt   lambda_
                                                                     2          
$#      xp        yp        zp        a1        a2        a3      macf
                                     0.0       0.0       1.0         1
$#      v1        v2        v3        d1        d2        d3
                                     0.0      -1.0       0.0
*EM_EP_CELLMODEL_TOMEK
$#     mid phiendmid phimidepi
         1      0.17      0.58
*MAT_ELASTIC
$#     mid        ro         e        pr        da        db    unused
         2     1e-06       1.0                                        
*EM_MAT_003
$#     mid     mtype   sigma11   sigma22   sigma33      beta        cm
         2         2       0.5       0.1       0.1     140.0      0.01
$# sigma12   sigma13   sigma21   sigma23   sigma31   sigma32      aopt   lambda_
                                                                     2          
$#      xp        yp        zp        a1        a2        a3      macf
                                     0.0       0.0       1.0         1
$#      v1        v2        v3        d1        d2        d3
                                     0.0      -1.0       0.0
*EM_EP_CELLMODEL_TOMEK
$#     mid phiendmid phimidepi
         2      0.17      0.58
*MAT_ELASTIC
$#     mid        ro         e        pr        da        db    unused
         7     1e-06       1.0                                        
*EM_MAT_003
$#     mid     mtype   sigma11   sigma22   sigma33      beta        cm
         7         2       0.5       0.1       0.1     140.0      0.01
$# sigma12   sigma13   sigma21   sigma23   sigma31   sigma32      aopt   lambda_
                                                                     2          
$#      xp        yp        zp        a1        a2        a3      macf
                                     0.0       0.0       1.0         1
$#      v1        v2        v3        d1        d2        d3
                                     0.0      -1.0       0.0
*EM_EP_CELLMODEL_TOMEK
$#     mid phiendmid phimidepi
         7      0.17      0.58
*END