*KEYWORD
*PART
$#                                                             heading
Left ventricle                                                        
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         1         1         1                                                  
*PART
$#                                                             heading
Right ventricle                                                       
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         2         1         2                                                  
*PART
$#                                                             heading
Septum                                                                
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         7         1         7                                                  
*SECTION_SOLID
$#   secid    elform       aet    unused    unused    unused    cohoff   gaskeit
         1        13         0                                                  
*END