*KEYWORD
*EM_EP_PURKINJE_NETWORK2
$#  purkid  buildnet      ssid       mid nodestart  pointstx  pointsty  pointstz
         1         1         3         4           66.736682 75.576275 353.68325
$# edgelen      ngen   nbrinit    nsplit   inodeid   iedgeid
         2        50         8         2     69654    303878
$# pmjtype pmjradiuspmjrestype    pmjres
         1       0.7         1     0.001
*EM_EP_PURKINJE_NETWORK2
$#  purkid  buildnet      ssid       mid nodestart  pointstx  pointsty  pointstz
         2         1         5         5           45.553674 77.017271 333.74565
$# edgelen      ngen   nbrinit    nsplit   inodeid   iedgeid
         2        50         8         2    139306    607754
$# pmjtype pmjradiuspmjrestype    pmjres
         1       0.7         1     0.001
*INCLUDE
$#                                                                      filename
parts.k                                                                         
*INCLUDE
$#                                                                      filename
nodes.k                                                                         
*INCLUDE
$#                                                                      filename
solid_elements.k                                                                
*INCLUDE
$#                                                                      filename
material.k                                                                      
*INCLUDE
$#                                                                      filename
segment_sets.k                                                                  
*INCLUDE
$#                                                                      filename
node_sets.k                                                                     
*INCLUDE
$#                                                                      filename
ep_settings.k                                                                   
*END