*KEYWORD
*MAT_295
$#     mid       rho      aopt
         1     0.001       2.0
$#   title     itype      beta        nu
ISO               -3       0.0     0.499
$#      k1        k2
   0.00236      1.75
$#   title     atype    intype        nf
ANISO             -1         0         1
$#   theta         a         b
       0.0       0.0       1.0
$#   ftype      fcid        k1        k2
         1         0   0.00049      9.01
$#   title    actype     acdir      acid     acthr        sf        ss        sn
ACTIVE             1         1         2       1.0       1.0       0.0       0.0
$#      t0    ca2ion   ca2ionm         n    taumax       stf         b        l0
                          4.35       2.0     0.125       0.0      4.75      1.58
$#       l     dtmax        mr        tr
      1.85     150.0    1048.9   -1629.0
$#      xp        yp        zp        a1        a2        a3      macf    unused
                                     1.0       0.0       0.0         1          
$#      v1        v2        v3        d1        d2        d3      beta       ref
                                     0.0       1.0       0.0                    
*MAT_295
$#     mid       rho      aopt
         2     0.001       2.0
$#   title     itype      beta        nu
ISO               -3       0.0     0.499
$#      k1        k2
   0.00236      1.75
$#   title     atype    intype        nf
ANISO             -1         0         1
$#   theta         a         b
       0.0       0.0       1.0
$#   ftype      fcid        k1        k2
         1         0   0.00049      9.01
$#   title    actype     acdir      acid     acthr        sf        ss        sn
ACTIVE             1         1         2       1.0       1.0       0.0       0.0
$#      t0    ca2ion   ca2ionm         n    taumax       stf         b        l0
                          4.35       2.0     0.125       0.0      4.75      1.58
$#       l     dtmax        mr        tr
      1.85     150.0    1048.9   -1629.0
$#      xp        yp        zp        a1        a2        a3      macf    unused
                                     1.0       0.0       0.0         1          
$#      v1        v2        v3        d1        d2        d3      beta       ref
                                     0.0       1.0       0.0                    
*MAT_295
$#     mid       rho      aopt
         3     0.001       2.0
$#   title     itype      beta        nu
ISO               -3       0.0     0.499
$#      k1        k2
   0.00236      1.75
$#   title     atype    intype        nf
ANISO             -1         0         1
$#   theta         a         b
       0.0       0.0       1.0
$#   ftype      fcid        k1        k2
         1         0   0.00049      9.01
$#   title    actype     acdir      acid     acthr        sf        ss        sn
ACTIVE             1         1         2       1.0       1.0       0.0       0.0
$#      t0    ca2ion   ca2ionm         n    taumax       stf         b        l0
                          4.35       2.0     0.125       0.0      4.75      1.58
$#       l     dtmax        mr        tr
      1.85     150.0    1048.9   -1629.0
$#      xp        yp        zp        a1        a2        a3      macf    unused
                                     1.0       0.0       0.0         1          
$#      v1        v2        v3        d1        d2        d3      beta       ref
                                     0.0       1.0       0.0                    
*DEFINE_CURVE_TITLE
$#                                                                         title
calcium_concentration                                                           
$#    lcid      sidr       sfa       sfo      offa      offo    dattyp     lcint
         2         0     800.0      4.35       0.0       0.0         0     10000
$#                a1                  o1
                 0.0                 0.0
               0.001                 1.0
0.900000000000000022                 1.0
                 1.0                 0.0
 1.00099999999999989                 1.0
 1.89999999999999991                 1.0
                 2.0                 0.0
 2.00099999999999989                 1.0
 2.89999999999999991                 1.0
                 3.0                 0.0
 3.00099999999999989                 1.0
 3.89999999999999991                 1.0
                 4.0                 0.0
 4.00100000000000033                 1.0
 4.90000000000000036                 1.0
                 5.0                 0.0
 5.00100000000000033                 1.0
 5.90000000000000036                 1.0
                 6.0                 0.0
 6.00100000000000033                 1.0
 6.90000000000000036                 1.0
                 7.0                 0.0
 7.00100000000000033                 1.0
 7.90000000000000036                 1.0
                 8.0                 0.0
 8.00099999999999945                 1.0
 8.90000000000000036                 1.0
                 9.0                 0.0
 9.00099999999999945                 1.0
 9.90000000000000036                 1.0
                10.0                 0.0
*END