*KEYWORD
*MAT_295
$#     mid       rho      aopt
         1     0.001       2.0
$#   title     itype      beta        nu
ISO               -3       0.0     0.499
$#      k1        k2
   0.00236      1.75
$#   title     atype    intype        nf
ANISO             -1         0         1
$#   theta         a         b
       0.0       0.0       1.0
$#   ftype      fcid        k1        k2
         1         0   0.00049      9.01
$#      xp        yp        zp        a1        a2        a3      macf    unused
                                     1.0       0.0       0.0         1          
$#      v1        v2        v3        d1        d2        d3      beta       ref
                                     0.0       1.0       0.0                    
*MAT_295
$#     mid       rho      aopt
         2     0.001       2.0
$#   title     itype      beta        nu
ISO               -3       0.0     0.499
$#      k1        k2
   0.00236      1.75
$#   title     atype    intype        nf
ANISO             -1         0         1
$#   theta         a         b
       0.0       0.0       1.0
$#   ftype      fcid        k1        k2
         1         0   0.00049      9.01
$#      xp        yp        zp        a1        a2        a3      macf    unused
                                     1.0       0.0       0.0         1          
$#      v1        v2        v3        d1        d2        d3      beta       ref
                                     0.0       1.0       0.0                    
*MAT_295
$#     mid       rho      aopt
         3     0.001       2.0
$#   title     itype      beta        nu
ISO               -3       0.0     0.499
$#      k1        k2
   0.00236      1.75
$#   title     atype    intype        nf
ANISO             -1         0         1
$#   theta         a         b
       0.0       0.0       1.0
$#   ftype      fcid        k1        k2
         1         0   0.00049      9.01
$#      xp        yp        zp        a1        a2        a3      macf    unused
                                     1.0       0.0       0.0         1          
$#      v1        v2        v3        d1        d2        d3      beta       ref
                                     0.0       1.0       0.0                    
*END