*KEYWORD
*EM_EP_PURKINJE_NETWORK2
$#  purkid  buildnet      ssid       mid nodestart  pointstx  pointsty  pointstz
         1         1         1         8            67.22632 75.676533 354.64464
$# edgelen      ngen   nbrinit    nsplit   inodeid   iedgeid
       1.5       200         3         4     61109    251857
$# pmjtype pmjradiuspmjrestype    pmjres
         2       1.5         1     0.001
*EM_EP_PURKINJE_NETWORK2
$#  purkid  buildnet      ssid       mid nodestart  pointstx  pointsty  pointstz
         2         1         3         9           45.478263 78.501683 333.32541
$# edgelen      ngen   nbrinit    nsplit   inodeid   iedgeid
       1.5       200         3         4    122216    503712
$# pmjtype pmjradiuspmjrestype    pmjres
         2       1.5         1     0.001
*INCLUDE
$#                                                                      filename
parts.k                                                                         
*INCLUDE
$#                                                                      filename
nodes.k                                                                         
*INCLUDE
$#                                                                      filename
solid_elements.k                                                                
*INCLUDE
$#                                                                      filename
material.k                                                                      
*INCLUDE
$#                                                                      filename
segment_sets.k                                                                  
*INCLUDE
$#                                                                      filename
node_sets.k                                                                     
*INCLUDE
$#                                                                      filename
ep_settings.k                                                                   
*END