*KEYWORD
*EM_EP_PURKINJE_NETWORK2
$#  purkid  buildnet      ssid       mid nodestart  pointstx  pointsty  pointstz
         1         1         1         4           66.957001 76.390788   352.544
$# edgelen      ngen   nbrinit    nsplit   inodeid   iedgeid
       1.5       200         3         4     42085    185522
$# pmjtype pmjradiuspmjrestype    pmjres
         2       1.5         1     0.001
*EM_EP_PURKINJE_NETWORK2
$#  purkid  buildnet      ssid       mid nodestart  pointstx  pointsty  pointstz
         2         1         3         5           44.994833 77.528966 333.07253
$# edgelen      ngen   nbrinit    nsplit   inodeid   iedgeid
       1.5       200         3         4     84168    371042
$# pmjtype pmjradiuspmjrestype    pmjres
         2       1.5         1     0.001
*INCLUDE
$#                                                                      filename
parts.k                                                                         
*INCLUDE
$#                                                                      filename
nodes.k                                                                         
*INCLUDE
$#                                                                      filename
solid_elements.k                                                                
*INCLUDE
$#                                                                      filename
material.k                                                                      
*INCLUDE
$#                                                                      filename
segment_sets.k                                                                  
*INCLUDE
$#                                                                      filename
node_sets.k                                                                     
*INCLUDE
$#                                                                      filename
ep_settings.k                                                                   
*END