*KEYWORD
*EM_EP_CELLMODEL_TENTUSSCHER
$#     mid
         1
$#       r         t         f        cm        vc       vsr       vss      pkna
  8314.472     310.0 96485.341     0.185  0.016404  0.001094 5.468e-05      0.03
$#      ko       nao       cao
       5.4     140.0       2.0
$#     gk1       gkr       gks       gna      gbna      gcal      gbca       gto
     5.405     0.153     0.392    14.838    0.0002  3.98e-05  0.000592     0.294
$#    gpca       gpk
    0.1238    0.0146
$#    pnak        km      kmna     knaca      ksat     alpha     gamma      kmca
     2.724       1.0      40.0    1000.0       0.1       2.5      0.35      1.38
$#   kmnai      kpca
      87.5    0.0005
$#      k1        k2        k3        k4        ec     maxsr     minsr
      0.15     0.045      0.06     0.005       1.5       2.5       1.0
$#    vrel     vleak     vxfer    vmaxup       kup
     0.102   0.00036    0.0038  0.006375   0.00025
$#    bufc     kbufc     bufsr    kbufsf     bufss    kbufss
       0.2     0.001      10.0       0.3       0.4   0.00025
$#       v        ki       nai       cai      cass      casr      rpri
    -85.23    136.89     8.604  0.000126   0.00036      3.64    0.9073
$#     xr1       xr2        xs         m         h         j         d         f
   0.00621    0.4712    0.0095   0.00172    0.7444    0.7045 3.373e-05    0.7888
$#      f2     fcass         s         r
    0.9755    0.9953  0.999998  2.42e-08
*EM_EP_CELLMODEL_TENTUSSCHER
$#     mid
         2
$#       r         t         f        cm        vc       vsr       vss      pkna
  8314.472     310.0 96485.341     0.185  0.016404  0.001094 5.468e-05      0.03
$#      ko       nao       cao
       5.4     140.0       2.0
$#     gk1       gkr       gks       gna      gbna      gcal      gbca       gto
     5.405     0.153     0.392    14.838    0.0002  3.98e-05  0.000592     0.294
$#    gpca       gpk
    0.1238    0.0146
$#    pnak        km      kmna     knaca      ksat     alpha     gamma      kmca
     2.724       1.0      40.0    1000.0       0.1       2.5      0.35      1.38
$#   kmnai      kpca
      87.5    0.0005
$#      k1        k2        k3        k4        ec     maxsr     minsr
      0.15     0.045      0.06     0.005       1.5       2.5       1.0
$#    vrel     vleak     vxfer    vmaxup       kup
     0.102   0.00036    0.0038  0.006375   0.00025
$#    bufc     kbufc     bufsr    kbufsf     bufss    kbufss
       0.2     0.001      10.0       0.3       0.4   0.00025
$#       v        ki       nai       cai      cass      casr      rpri
    -85.23    136.89     8.604  0.000126   0.00036      3.64    0.9073
$#     xr1       xr2        xs         m         h         j         d         f
   0.00621    0.4712    0.0095   0.00172    0.7444    0.7045 3.373e-05    0.7888
$#      f2     fcass         s         r
    0.9755    0.9953  0.999998  2.42e-08
*EM_EP_CELLMODEL_TENTUSSCHER
$#     mid
         7
$#       r         t         f        cm        vc       vsr       vss      pkna
  8314.472     310.0 96485.341     0.185  0.016404  0.001094 5.468e-05      0.03
$#      ko       nao       cao
       5.4     140.0       2.0
$#     gk1       gkr       gks       gna      gbna      gcal      gbca       gto
     5.405     0.153     0.392    14.838    0.0002  3.98e-05  0.000592     0.294
$#    gpca       gpk
    0.1238    0.0146
$#    pnak        km      kmna     knaca      ksat     alpha     gamma      kmca
     2.724       1.0      40.0    1000.0       0.1       2.5      0.35      1.38
$#   kmnai      kpca
      87.5    0.0005
$#      k1        k2        k3        k4        ec     maxsr     minsr
      0.15     0.045      0.06     0.005       1.5       2.5       1.0
$#    vrel     vleak     vxfer    vmaxup       kup
     0.102   0.00036    0.0038  0.006375   0.00025
$#    bufc     kbufc     bufsr    kbufsf     bufss    kbufss
       0.2     0.001      10.0       0.3       0.4   0.00025
$#       v        ki       nai       cai      cass      casr      rpri
    -85.23    136.89     8.604  0.000126   0.00036      3.64    0.9073
$#     xr1       xr2        xs         m         h         j         d         f
   0.00621    0.4712    0.0095   0.00172    0.7444    0.7045 3.373e-05    0.7888
$#      f2     fcass         s         r
    0.9755    0.9953  0.999998  2.42e-08
*EM_EP_CELLMODEL_TENTUSSCHER
$#     mid
         9
$#       r         t         f        cm        vc       vsr       vss      pkna
  8314.472     310.0 96485.341     0.185  0.016404  0.001094 5.468e-05      0.03
$#      ko       nao       cao
       5.4     140.0       2.0
$#     gk1       gkr       gks       gna      gbna      gcal      gbca       gto
     5.405     0.153     0.392    14.838    0.0002  3.98e-05  0.000592     0.294
$#    gpca       gpk
    0.1238    0.0146
$#    pnak        km      kmna     knaca      ksat     alpha     gamma      kmca
     2.724       1.0      40.0    1000.0       0.1       2.5      0.35      1.38
$#   kmnai      kpca
      87.5    0.0005
$#      k1        k2        k3        k4        ec     maxsr     minsr
      0.15     0.045      0.06     0.005       1.5       2.5       1.0
$#    vrel     vleak     vxfer    vmaxup       kup
     0.102   0.00036    0.0038  0.006375   0.00025
$#    bufc     kbufc     bufsr    kbufsf     bufss    kbufss
       0.2     0.001      10.0       0.3       0.4   0.00025
$#       v        ki       nai       cai      cass      casr      rpri
    -85.23    136.89     8.604  0.000126   0.00036      3.64    0.9073
$#     xr1       xr2        xs         m         h         j         d         f
   0.00621    0.4712    0.0095   0.00172    0.7444    0.7045 3.373e-05    0.7888
$#      f2     fcass         s         r
    0.9755    0.9953  0.999998  2.42e-08
*EM_EP_CELLMODEL_TENTUSSCHER
$#     mid
        10
$#       r         t         f        cm        vc       vsr       vss      pkna
  8314.472     310.0 96485.341     0.185  0.016404  0.001094 5.468e-05      0.03
$#      ko       nao       cao
       5.4     140.0       2.0
$#     gk1       gkr       gks       gna      gbna      gcal      gbca       gto
     5.405     0.153     0.392    14.838    0.0002  3.98e-05  0.000592     0.294
$#    gpca       gpk
    0.1238    0.0146
$#    pnak        km      kmna     knaca      ksat     alpha     gamma      kmca
     2.724       1.0      40.0    1000.0       0.1       2.5      0.35      1.38
$#   kmnai      kpca
      87.5    0.0005
$#      k1        k2        k3        k4        ec     maxsr     minsr
      0.15     0.045      0.06     0.005       1.5       2.5       1.0
$#    vrel     vleak     vxfer    vmaxup       kup
     0.102   0.00036    0.0038  0.006375   0.00025
$#    bufc     kbufc     bufsr    kbufsf     bufss    kbufss
       0.2     0.001      10.0       0.3       0.4   0.00025
$#       v        ki       nai       cai      cass      casr      rpri
    -85.23    136.89     8.604  0.000126   0.00036      3.64    0.9073
$#     xr1       xr2        xs         m         h         j         d         f
   0.00621    0.4712    0.0095   0.00172    0.7444    0.7045 3.373e-05    0.7888
$#      f2     fcass         s         r
    0.9755    0.9953  0.999998  2.42e-08
*EM_EP_CELLMODEL_TENTUSSCHER
$#     mid
        11
$#       r         t         f        cm        vc       vsr       vss      pkna
  8314.472     310.0 96485.341     0.185  0.016404  0.001094 5.468e-05      0.03
$#      ko       nao       cao
       5.4     140.0       2.0
$#     gk1       gkr       gks       gna      gbna      gcal      gbca       gto
     5.405     0.153     0.392    14.838    0.0002  3.98e-05  0.000592     0.294
$#    gpca       gpk
    0.1238    0.0146
$#    pnak        km      kmna     knaca      ksat     alpha     gamma      kmca
     2.724       1.0      40.0    1000.0       0.1       2.5      0.35      1.38
$#   kmnai      kpca
      87.5    0.0005
$#      k1        k2        k3        k4        ec     maxsr     minsr
      0.15     0.045      0.06     0.005       1.5       2.5       1.0
$#    vrel     vleak     vxfer    vmaxup       kup
     0.102   0.00036    0.0038  0.006375   0.00025
$#    bufc     kbufc     bufsr    kbufsf     bufss    kbufss
       0.2     0.001      10.0       0.3       0.4   0.00025
$#       v        ki       nai       cai      cass      casr      rpri
    -85.23    136.89     8.604  0.000126   0.00036      3.64    0.9073
$#     xr1       xr2        xs         m         h         j         d         f
   0.00621    0.4712    0.0095   0.00172    0.7444    0.7045 3.373e-05    0.7888
$#      f2     fcass         s         r
    0.9755    0.9953  0.999998  2.42e-08
*EM_EP_CELLMODEL_TENTUSSCHER
$#     mid
        12
$#       r         t         f        cm        vc       vsr       vss      pkna
  8314.472     310.0 96485.341     0.185  0.016404  0.001094 5.468e-05      0.03
$#      ko       nao       cao
       5.4     140.0       2.0
$#     gk1       gkr       gks       gna      gbna      gcal      gbca       gto
     5.405     0.153     0.392    14.838    0.0002  3.98e-05  0.000592     0.294
$#    gpca       gpk
    0.1238    0.0146
$#    pnak        km      kmna     knaca      ksat     alpha     gamma      kmca
     2.724       1.0      40.0    1000.0       0.1       2.5      0.35      1.38
$#   kmnai      kpca
      87.5    0.0005
$#      k1        k2        k3        k4        ec     maxsr     minsr
      0.15     0.045      0.06     0.005       1.5       2.5       1.0
$#    vrel     vleak     vxfer    vmaxup       kup
     0.102   0.00036    0.0038  0.006375   0.00025
$#    bufc     kbufc     bufsr    kbufsf     bufss    kbufss
       0.2     0.001      10.0       0.3       0.4   0.00025
$#       v        ki       nai       cai      cass      casr      rpri
    -85.23    136.89     8.604  0.000126   0.00036      3.64    0.9073
$#     xr1       xr2        xs         m         h         j         d         f
   0.00621    0.4712    0.0095   0.00172    0.7444    0.7045 3.373e-05    0.7888
$#      f2     fcass         s         r
    0.9755    0.9953  0.999998  2.42e-08
*EM_EP_CELLMODEL_TENTUSSCHER
$#     mid
        13
$#       r         t         f        cm        vc       vsr       vss      pkna
  8314.472     310.0 96485.341     0.185  0.016404  0.001094 5.468e-05      0.03
$#      ko       nao       cao
       5.4     140.0       2.0
$#     gk1       gkr       gks       gna      gbna      gcal      gbca       gto
     5.405     0.153     0.392    14.838    0.0002  3.98e-05  0.000592     0.294
$#    gpca       gpk
    0.1238    0.0146
$#    pnak        km      kmna     knaca      ksat     alpha     gamma      kmca
     2.724       1.0      40.0    1000.0       0.1       2.5      0.35      1.38
$#   kmnai      kpca
      87.5    0.0005
$#      k1        k2        k3        k4        ec     maxsr     minsr
      0.15     0.045      0.06     0.005       1.5       2.5       1.0
$#    vrel     vleak     vxfer    vmaxup       kup
     0.102   0.00036    0.0038  0.006375   0.00025
$#    bufc     kbufc     bufsr    kbufsf     bufss    kbufss
       0.2     0.001      10.0       0.3       0.4   0.00025
$#       v        ki       nai       cai      cass      casr      rpri
    -85.23    136.89     8.604  0.000126   0.00036      3.64    0.9073
$#     xr1       xr2        xs         m         h         j         d         f
   0.00621    0.4712    0.0095   0.00172    0.7444    0.7045 3.373e-05    0.7888
$#      f2     fcass         s         r
    0.9755    0.9953  0.999998  2.42e-08
*EM_EP_CELLMODEL_TENTUSSCHER
$#     mid
        14
$#       r         t         f        cm        vc       vsr       vss      pkna
  8314.472     310.0 96485.341     0.185  0.016404  0.001094 5.468e-05      0.03
$#      ko       nao       cao
       5.4     140.0       2.0
$#     gk1       gkr       gks       gna      gbna      gcal      gbca       gto
     5.405     0.153     0.392    14.838    0.0002  3.98e-05  0.000592     0.294
$#    gpca       gpk
    0.1238    0.0146
$#    pnak        km      kmna     knaca      ksat     alpha     gamma      kmca
     2.724       1.0      40.0    1000.0       0.1       2.5      0.35      1.38
$#   kmnai      kpca
      87.5    0.0005
$#      k1        k2        k3        k4        ec     maxsr     minsr
      0.15     0.045      0.06     0.005       1.5       2.5       1.0
$#    vrel     vleak     vxfer    vmaxup       kup
     0.102   0.00036    0.0038  0.006375   0.00025
$#    bufc     kbufc     bufsr    kbufsf     bufss    kbufss
       0.2     0.001      10.0       0.3       0.4   0.00025
$#       v        ki       nai       cai      cass      casr      rpri
    -85.23    136.89     8.604  0.000126   0.00036      3.64    0.9073
$#     xr1       xr2        xs         m         h         j         d         f
   0.00621    0.4712    0.0095   0.00172    0.7444    0.7045 3.373e-05    0.7888
$#      f2     fcass         s         r
    0.9755    0.9953  0.999998  2.42e-08
*END