*KEYWORD
*PART
$#                                                             heading
Left ventricle                                                        
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         1         1         1                                                  
*PART
$#                                                             heading
Right ventricle                                                       
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         2         1         2                                                  
*PART
$#                                                             heading
Septum                                                                
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         3         1         3                                                  
*PART
$#                                                             heading
Left atrium                                                           
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         4         1         4                                                  
*PART
$#                                                             heading
Right atrium                                                          
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         5         1         5                                                  
*PART
$#                                                             heading
Aorta                                                                 
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         6         1         6                                                  
*PART
$#                                                             heading
Pulmonary artery                                                      
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         7         1         7                                                  
*SECTION_SOLID
$#   secid    elform       aet    unused    unused    unused    cohoff   gaskeit
         1        13         0                                                  

*END