name: Build documentation
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

permissions:
  contents: write

env:
  MAIN_PYTHON_VERSION: 3.9

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install package
        run: pip install -e .

      - name: Install documentation build requirements
        run: pip install -r requirements_docs.txt

      - name: Build Documentation
        run: |
          make -C doc clean
          make -C doc html
# make -C doc html SPHINXOPTS="-j auto -W --keep-going"
      - name: Upload HTML Documentation
        uses: actions/upload-artifact@v2
        with:
          name: HTML-Documentation
          path: doc/_build/html
          retention-days: 7

      - name: Deploy
        # if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          branch: build-documentation
          folder: doc/_build/html
          clean: true

# jobs:
#   build:
#     name: Style Check
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout project
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: ${{ env.MAIN_PYTHON_VERSION }}

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip pre-commit

#       - name: Pre-commit install
#         run: |
#           pre-commit install
#       - name: Run pre-commit
#         run: |          
#           pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )