# GitHub workflow for setting up unit-testing involving pyfluent 
# - use docker to pull Fluent image
name: Fluent Docker Test
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION: 3.8

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Tests requiring PyFluent
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.REPO_DOWNLOAD_PAT }}

      - name: Pull 22.2 Fluent docker image
        run: | 
          docker pull ghcr.io/pyansys/pyfluent:v22.2.0
          docker image prune -f

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .         

      - name: Install testing dependencies
        run: |
          python -m pip install -r requirements_tests.txt

      - name: Start unit testing requiring PyFluent 22.2.0
        run: |
          python -m pytest tests/heart/test_pyfluent.py
#        continue-on-error: true
        env:
          ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
          PYFLUENT_START_INSTANCE: 0
          PYFLUENT_LAUNCH_CONTAINER: 1          
          FLUENT_IMAGE_TAG: v22.2.0