# GitHub workflow for functional tests
# Tests consistencty of model being generated
name: Test model generation-v2-fh
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize', 'ready_for_review']
  push:
    tags:
      - "*"
    branches:
      - main
  workflow_dispatch:

# Required env variables for pyfluent
env:
  MAIN_PYTHON_VERSION: 3.9
  ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
  PYFLUENT_START_INSTANCE: 0
  PYFLUENT_LAUNCH_CONTAINER: 1
  FLUENT_IMAGE_TAG: v22.2.0


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: Tests requiring PyFluent
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      # Login to Github container registry and pull Fluent image. if image-cach doesn't exist
      - name: Login to GitHub Container Registry
        # if: steps.image-cache.outputs.cache-hit != 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.REPO_DOWNLOAD_PAT }}

      - name: Pull 22.2 Fluent docker image
        run: |
          docker pull ghcr.io/ansys/pyfluent:$FLUENT_IMAGE_TAG
          docker image prune -f

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install git+https://${{secrets.REPO_DOWNLOAD_PAT}}@github.com/ansys/dynalib.git@main

      - name: Install testing dependencies
        run: |
          python -m pip install .[tests]

      # - name: Test model generation v0.2 - bi-ventricle
      #   env:
      #     ANSYS_HEART_MODEL_VERSION: "v0.2"
      #   continue-on-error: false
      #   run: |
      #     python -m pytest -v tests/heart/preprocessor/test_biventricle_v0-2.py

      - name: Test model generation v0.2 full-heart
        env:
          ANSYS_HEART_MODEL_VERSION: "v0.2"
        continue-on-error: false
        run: |
          python -m pytest -v tests/heart/preprocessor/test_fullheart_v0-2.py